/**
 * The full database schema.
 *
 * `auth-schema.ts` is generated by the Better Auth CLI and must not be edited
 * by hand -- regenerate it with:
 *
 *   pnpm db:auth
 *
 * `app-schema.ts` holds everything this product owns.
 */
export * from "./auth-schema";
export * from "./app-schema";
